import webpush from 'npm:web-push@3.6.7';
const base=Deno.env.get('SUPABASE_URL')!,key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const origin='https://viettrip-vietnam-map.pages.dev';
const cors={'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Headers':'content-type,apikey,authorization','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Cache-Control':'no-store'};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{...cors,'Content-Type':'application/json'}});
async function db(path:string,method='GET',body?:unknown){const r=await fetch(base+'/rest/v1/'+path,{method,headers:{apikey:key,Authorization:'Bearer '+key,'Content-Type':'application/json',Prefer:'return=representation'},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok)throw new Error('database request failed');return r.status===204?null:await r.json();}
const validId=(id:unknown)=>typeof id==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id);
function validSubscription(s:any){try{const u=new URL(s.endpoint);return u.protocol==='https:'&&!u.port&&!u.username&&!u.password&&!u.hash&&s.endpoint.length<2048&&(u.hostname==='fcm.googleapis.com'||u.hostname==='updates.push.services.mozilla.com'||u.hostname==='web.push.apple.com'||u.hostname.endsWith('.push.apple.com'))&&/^[A-Za-z0-9_-]{87}$/.test(s.keys.p256dh)&&/^[A-Za-z0-9_-]{22}$/.test(s.keys.auth)}catch{return false}}
async function hash(value:string){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function config(){let [c]=await db('chat_push_config?id=eq.true');if(!c.vapid){await db('chat_push_config?id=eq.true&vapid=is.null','PATCH',{vapid:webpush.generateVAPIDKeys()});[c]=await db('chat_push_config?id=eq.true')}return c;}
async function state(member:string){const rows=await db('chat_push_inbox?member_id=eq.'+member+'&read_at=is.null&select=message_id&order=created_at.asc&limit=1000');return {count:rows.length,ids:rows.map((r:any)=>r.message_id)};}
async function dispatch(c:any){const jobs=await db('rpc/claim_chat_push','POST',{});let delivered=0;
 await Promise.all(jobs.map(async(job:any)=>{let status=0;try{const [inbox]=await db('chat_push_inbox?message_id=eq.'+job.message_id);const [sub]=await db('chat_push_subscriptions?id=eq.'+job.subscription_id);if(!inbox||inbox.read_at||!sub){await db('chat_push_deliveries?id=eq.'+job.id,'PATCH',{done:true});return}const [message]=await db('chat_messages?id=eq.'+job.message_id+'&select=id,nickname,body');if(!message)return;if(!validSubscription(sub.subscription))throw new Error('invalid push endpoint');const {count}=await state(inbox.member_id);const payload=JSON.stringify({title:'베트남맵 · 새 답장',body:message.nickname+'님이 내 글에 답장했습니다.',messageId:message.id,count,url:origin+'/?chat_reply='+message.id});const details=webpush.generateRequestDetails(sub.subscription,payload,{TTL:3600,urgency:'normal',topic:job.message_id.replaceAll('-',''),vapidDetails:{subject:origin,...c.vapid}});const response=await fetch(details.endpoint,{method:'POST',headers:details.headers,body:details.body,redirect:'error',signal:AbortSignal.timeout(10000)});status=response.status;if(status===404||status===410){await db('chat_push_subscriptions?id=eq.'+job.subscription_id,'DELETE');return}if(response.ok)delivered++;await db('chat_push_deliveries?id=eq.'+job.id,'PATCH',{done:response.ok,last_status:status});}catch{await db('chat_push_deliveries?id=eq.'+job.id,'PATCH',{last_status:status}).catch(()=>{})}}));return {processed:jobs.length,delivered};}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response(null,{headers:cors});try{
 const action=new URL(req.url).pathname.split('/').pop();
 if(action==='config'&&req.method==='GET'){const c=await config();return json({publicKey:c.vapid.publicKey});}
 if(action==='dispatch'){const [c]=await db('chat_push_config?id=eq.true');if(req.method!=='POST'||req.headers.get('x-push-secret')!==c.dispatch_secret)return json({error:'Unauthorized'},401);return json(await dispatch(await config()));}
 if(req.method!=='POST')return json({error:'Not found'},404);
 if(req.headers.get('origin')!==origin)return json({error:'Origin not allowed'},403);
 const raw=await req.text();if(raw.length>6000)return json({error:'Request too large'},413);const data=JSON.parse(raw);if(!validId(data.deviceId))return json({error:'회원 연결을 확인해 주세요.'},401);
 const member=await db('rpc/chat_push_member','POST',{p_device_id:data.deviceId});if(!member)return json({error:'회원 정보를 먼저 불러와 주세요.'},401);
 if(action==='subscribe'){if(!validSubscription(data.subscription))return json({error:'지원되지 않는 푸시 주소입니다.'},400);const id=await hash(data.subscription.endpoint);const [old]=await db('chat_push_subscriptions?id=eq.'+id);if(old&&old.member_id!==member)return json({error:'기기 연결을 다시 설정해 주세요.'},409);const all=await db('chat_push_subscriptions?member_id=eq.'+member+'&select=id');if(!old&&all.length>=8)return json({error:'알림은 최대 8개 기기까지 등록할 수 있습니다.'},409);if(old)await db('chat_push_subscriptions?id=eq.'+id,'PATCH',{subscription:data.subscription,updated_at:new Date().toISOString()});else await db('chat_push_subscriptions','POST',{id,member_id:member,subscription:data.subscription});return json({ok:true,...await state(member)});}
 if(action==='unsubscribe'){if(typeof data.endpoint!=='string')return json({error:'Invalid request'},400);await db('chat_push_subscriptions?id=eq.'+await hash(data.endpoint)+'&member_id=eq.'+member,'DELETE');return json({ok:true});}
 if(action==='read'){const ids=Array.isArray(data.ids)?data.ids.filter(validId).slice(0,200):[];if(ids.length)await db('chat_push_inbox?member_id=eq.'+member+'&message_id=in.('+ids.join(',')+')','PATCH',{read_at:new Date().toISOString()});return json(await state(member));}
 if(action==='state')return json(await state(member));return json({error:'Not found'},404);
 }catch{return json({error:'알림 연결에 실패했습니다. 다시 시도해 주세요.'},503)}});
