const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {JSDOM}=require('jsdom');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
(async()=>{
 const dom=new JSDOM(read('index.html'),{url:'https://map.test',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;
 const run=s=>vm.runInContext(s,dom.getInternalVMContext());w.matchMedia=()=>({matches:false});
 for(const file of fs.readdirSync(path.join(root,'assets/js')).filter(n=>/^0[1-8]-/.test(n)).sort())run(read('assets/js/'+file));
 run(read('assets/js/place-photos.js'));run(read('assets/js/ai-place-hours.js'));
 run(`const data={places:[],reviews:[{id:'keep-review',text:'원본 후기'}]};db=()=>data;state.sharedDbLoading=false;state.city='hcmc';`);
 run(read('assets/js/ai-google-search.js'));run(read('assets/js/ai-map-search.js'));
 const intent={relevant:true,city:'hcmc',district:'12',area:'',category:'spa',subcategory:'',terms:['왁싱'],preferences:[],visitToday:false,benefit:false,recommended:false,nearby:false,unsupported:[]};
 const boundaries=JSON.parse(read('assets/data/admin/hcmc.geojson')).features;
 const place=(id,rating=4.5,count=100,address='Quận 12, Hồ Chí Minh')=>({id,displayName:'Waxing '+id,formattedAddress:address,location:{lat:10.867,lng:106.654},rating,userRatingCount:count,businessStatus:'OPERATIONAL',types:['beauty_salon'],addressComponents:[{types:['country'],shortText:'VN'}],attributions:[]});
 const raw=[place('five',5,10),place('many',5,200),place('low',3.9),place('norating',undefined,0),place('eleven',5,200,'Quận 11, Hồ Chí Minh'),{...place('closed'),businessStatus:'CLOSED_PERMANENTLY'},place('many',5,200),{...place('foreign'),addressComponents:[{types:['country'],shortText:'US'}]}];
 const rows=w.AIGoogleSearch.rowsFrom(raw,intent,{boundaries});
 assert.deepEqual(Array.from(rows,r=>r.placeId),['many','five']);assert.equal(rows[0].name,'Waxing many','preserve original business name');
 const specific=w.AIGoogleSearch.rowsFrom([{...place('broad',5,999),displayName:'일반 스파'},place('specific',4.5,20)],intent,{boundaries});assert.equal(specific.length,1,'generic spas do not satisfy a waxing request');assert.equal(specific[0].placeId,'specific');
 assert.match(w.AIGoogleSearch.queryFor(intent),/waxing Quận 12 Ho Chi Minh City Vietnam/);assert(!w.AIGoogleSearch.queryFor(intent).includes('barber'));
 const bounds=w.AIGoogleSearch.boundsFor(intent,boundaries);assert(bounds.north>10.867&&bounds.south<10.867&&bounds.west<106.654&&bounds.east>106.654);
 assert.equal(w.AIGoogleSearch.rowsFrom([place('duplicate')],intent,{places:[{id:'registered',googlePlaceId:'duplicate'}]}).length,0);
 assert.equal(w.AIGoogleSearch.rowsFrom([place('outside')],{...intent,nearby:true},{nearby:{lat:10.7,lng:106.6,radius:100}}).length,0);
 let request,calls=0,finish;
 w.google={maps:{places:{Place:{searchByText:async r=>{calls++;request=r;return {places:raw}}}}}};
 const found=await w.AIGoogleSearch.search(intent,{boundaries});assert.equal(found.length,2);assert.equal(calls,1);assert.equal(request.maxResultCount,20);assert.equal(request.minRating,4);assert(request.locationRestriction);assert(!request.locationBias);assert(!request.fields.includes('currentOpeningHours'));
 await w.AIGoogleSearch.search({...intent,visitToday:true},{boundaries});assert(request.fields.includes('currentOpeningHours'));
 w.google.maps.places.Place.searchByText=()=>new Promise(resolve=>{finish=resolve});
 const abort=new w.AbortController(),pending=w.AIGoogleSearch.search(intent,{signal:abort.signal});abort.abort();await assert.rejects(pending,e=>e.name==='AbortError');finish({places:raw});
 let opened;w.PlaceSearch={dismiss(){},openMember:id=>{opened=id},openGoogle:row=>{opened=row.placeId}};
 w.fetch=async url=>({ok:true,json:async()=>String(url).includes('geojson')?{features:boundaries}:{intent}});
 const input=w.document.getElementById('aiMapQuestion'),form=w.document.getElementById('aiMapForm'),submit=async text=>{input.value=text;input.dispatchEvent(new w.Event('input'));form.dispatchEvent(new w.Event('submit',{cancelable:true}));await new Promise(r=>setTimeout(r,10));};
 w.google.maps.places.Place.searchByText=async()=>({places:raw});
 await submit('12군 왁싱샵 추천해줘');
 assert.equal(w.document.querySelectorAll('.aiGoogleResult').length,2,'no member records must not block Google discovery');
 assert.equal(w.document.querySelectorAll('.aiMemberResult').length,0);
 assert.match(w.document.querySelector('.aiGoogleResult').textContent,/Google ★ 5.0 · 후기 200개/);
 w.document.querySelector('.aiGoogleResult').click();assert.equal(opened,'many');assert(w.document.getElementById('aiMapPanel').hidden);
 run(`data.places.push({id:'member',googlePlaceId:'five',name:'회원 왁싱샵',category:'barber',address:'Quận 12, Hồ Chí Minh',lat:10.867,lng:106.654,initialRating:4,memberBenefit:true,tags:['강추업소']},{id:'massage-only',name:'일반 마사지',category:'spa',address:'Quận 12, Hồ Chí Minh',lat:10.867,lng:106.654});`);
 const before=run('JSON.stringify(data)');await submit('12군 왁싱샵 다시 추천해줘');
 assert.equal(w.document.querySelectorAll('.aiMemberResult').length,1,'waxing mentioned in a barber registration is eligible; generic massage is not');
 assert.equal(w.document.querySelectorAll('.aiGoogleResult').length,1,'registered branch is deduplicated');
 assert.equal(w.document.querySelector('.aiResult').dataset.placeId,'member','member always comes before higher Google rating');
 assert.equal(w.document.querySelectorAll('.aiGoogleResult .aiBenefit,.aiGoogleResult .aiRecommended').length,0);
 const stable=w.document.querySelector('.aiMemberResult');
 w.google.maps.places.Place.searchByText=()=>new Promise(resolve=>{finish=resolve});await submit('12군 왁싱샵 추천해 주세요');
 const during=w.document.querySelector('.aiMemberResult');finish({places:raw});await new Promise(r=>setTimeout(r,5));assert.strictEqual(w.document.querySelector('.aiMemberResult'),during,'Google completion cannot replace a member card during a tap');
 await submit('12군 왁싱샵 추천');w.document.getElementById('aiMapClear').click();finish({places:raw});await new Promise(r=>setTimeout(r,5));assert.equal(w.document.querySelectorAll('.aiResult').length,0,'clear suppresses late Google response');
 w.google.maps.places.Place.searchByText=async()=>{throw Error('REQUEST_DENIED')};await submit('12군 왁싱샵');assert(w.document.querySelector('.aiMemberResult'));assert.match(w.document.getElementById('aiGoogleSection').textContent,/연결하지 못/);assert(w.document.querySelector('.aiRetry'));
 w.google.maps.places.Place.searchByText=async()=>({places:raw});w.document.querySelector('.aiRetry').click();await new Promise(r=>setTimeout(r,5));assert(w.document.querySelector('.aiGoogleResult'));
 assert.equal(run('JSON.stringify(data)'),before,'no places/reviews are written during search, detail selection, abort or retry');
 dom.window.close();console.log('PASS Google discovery, district 12, ratings/count order, member priority, deduplication, stable taps, cancellation, failures and read-only data');
})().catch(e=>{console.error(e);process.exitCode=1});
