const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {JSDOM}=require('jsdom'),root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
(async()=>{
 const api=await import('data:text/javascript;base64,'+Buffer.from(read('functions/api/ask-map.js')).toString('base64'));
 const base={relevant:false,city:'hcmc',district:'',area:'',category:'',subcategory:'',terms:[],preferences:[],benefit:false,recommended:false,nearby:false,visitToday:false,unsupported:[]};
 const parse=(q,wrong={})=>api.clarifyIntent(api.validateIntent({...base,...wrong},'hcmc'),q);
 const banh=parse('호치민 가장 유명한 반미집?',{category:'restaurant',subcategory:'중식',terms:['반미','유명한']});assert(banh.relevant);assert.equal(banh.subcategory,'');assert.equal(banh.sortBy,'popular');assert.deepEqual(banh.terms,['반미']);
 const bakery=parse('호치민에서 가장 유명한 빵집 어디야?',{category:'shopping',terms:['빵집']});assert.equal(bakery.category,'cafe');assert.equal(bakery.subcategory,'베이커리');assert(bakery.relevant);
 const rental=parse('오토바이 빌리고 싶은데 어디 가야해?');assert.equal(rental.service,'motorbike_rental');assert(rental.relevant);assert.deepEqual(rental.terms,['오토바이 대여']);
 const ferry=parse('호치민에서 푸꿕으로 배를 타고 싶어 어디서 표를 사?',{unsupported:['여러 도시']});assert.equal(ferry.guide,'hcmc_phuquoc_ferry');assert.equal(ferry.unsupported.length,0);
 const hotel=parse('1군에 있는 4성급 호텔 후기 좋은 호텔 중에서 가장 좋은 곳',{terms:['4성급'],unsupported:['호텔 성급']});assert(hotel.relevant);assert.equal(hotel.hotelStars,4);assert.equal(hotel.district,'1');assert.equal(hotel.sortBy,'top_rated');assert.equal(hotel.terms.length,0);assert.equal(hotel.unsupported.length,0);
 const budget=parse('로컬 가라오케 중 500만동 정도로 놀만한 곳 찾아줘',{category:'karaoke',terms:['로컬','500만동'],unsupported:['500만동']});assert.equal(budget.subcategory,'로컬 KTV');assert.deepEqual(budget.budget,{amount:5000000,currency:'VND'});assert.equal(budget.unsupported.length,0);assert.equal(budget.terms.length,0);
 const cheap=parse('호치민에서 가격 저렴한 식당 찾아줘');assert.equal(cheap.sortBy,'cheap');assert(cheap.showPrice);
 const atmosphere=parse('분위기 좋은 1군 식당 찾아줘');assert.equal(atmosphere.sortBy,'atmosphere');
 assert.deepEqual(parse('1군 후기 좋은 호텔 중 가장 좋은 곳',{unsupported:['후기 좋은','가장 좋은 곳','평점 5점 이상']}).unsupported,['평점 5점 이상'],'soft rankings cannot block search; hard rating condition survives');
 for(const question of ['로컬 가라오케 중 500만동 정도로 놀만한 곳 찾아줘','1군에 있는 4성급 호텔 후기 좋은 호텔 중에서 가장 좋은 곳','호치민에서 푸꿕으로 배를 타고 싶어 어디서 표를 사','오토바이 빌리고 싶은데 어디 가야해?','호치민 가장 유명한 반미집?','호치민에서 가장 유명한 빵집 어디야?','1군에서 분위기 좋은 식당 찾아줘','1군에서 가격 저렴한 식당 찾아줘']){
   assert(api.literalIntent(question,'hcmc'),question);
   const response=await api.onRequest({request:new Request('https://map.test/api/ask-map',{method:'POST',headers:{origin:'https://map.test','content-type':'application/json'},body:JSON.stringify({query:question,city:'hcmc'})}),env:{AI:{run:()=>{throw Error('MODEL_UNAVAILABLE')}}}});
   assert.equal(response.status,200,'fully understood question works during model failure');
 }
 for(const question of ['부산에서 유명한 빵집','지금 영업 중인 빵집','호치민과 하노이에서 빵집 찾아줘','1군 말고 저렴한 식당','2명이 20만동 이하 식당','주말에 문 여는 빵집','글루텐 없는 빵집','1군에서 동태탕 식당'])assert.equal(api.literalIntent(question,'hcmc'),null,'never drop unknown constraint: '+question);
 assert.equal(api.literalIntent('푸꿕 호텔 찾아줘','hcmc').city,'phuquoc');
 const dom=new JSDOM(read('index.html'),{url:'https://map.test',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,run=s=>vm.runInContext(s,dom.getInternalVMContext());w.matchMedia=()=>({matches:false});
 for(const f of fs.readdirSync(path.join(root,'assets/js')).filter(n=>/^0[1-8]-/.test(n)).sort())run(read('assets/js/'+f));
 for(const f of ['place-photos','ai-search-insights','ai-google-search','ai-map-search'])run(read('assets/js/'+f+'.js'));
 const I=w.AISearchInsights;
 assert.equal(I.price({priceRange:{startPrice:{units:'50000',currencyCode:'VND'},endPrice:{units:'100000',currencyCode:'VND'}}}).label,'50,000 VND–100,000 VND');
 assert.equal(I.price({priceRange:{startPrice:{units:'100',currencyCode:'USD'},endPrice:{units:'1',currencyCode:'USD'}}}).known,false);
 assert.equal(I.price({priceLevel:'INEXPENSIVE'}).label,'저렴');assert.equal(I.price({priceLevel:'VeryExpensive'}).label,'매우 높은 가격대');assert.equal(I.price({}).known,false);
 const priced=(low,currency='VND',level=null)=>({insights:{price:{known:true,low,currency,level}}});
 const mixed=[priced(100,'VND',1),priced(50,'VND',2),priced(75),{insights:{price:{known:true,level:1}}},priced(2,'USD'),{insights:{price:{known:false}}}];
 for(const a of mixed)for(const b of mixed)for(const c of mixed)if(I.compare(a,b,cheap)<=0&&I.compare(b,c,cheap)<=0)assert(I.compare(a,c,cheap)<=0,'mixed price formats have a consistent order');
 assert.equal(I.hotelInfo([{label:'Google 후기',text:'평점 4점, 호텔 좋았어요'}],4).kind,'unknown');assert.equal(I.hotelInfo([{label:'등록 정보',text:'3성급 호텔'}],4).kind,'different');
 assert.equal(I.preferenceEvidence([{label:'회원 후기',text:'분위기가 별로였고 시끄러웠어요'}],atmosphere).hits.length,0);
 assert.equal(I.preferenceEvidence([{label:'Google 후기',text:'Great atmosphere and lovely interior.'}],atmosphere).hits.length,1);
 const address='Quận 1, Hồ Chí Minh',position={lat:10.779,lng:106.702};
 const data={places:[{id:'local',googlePlaceId:'g-local',name:'회원 등록 식당',category:'restaurant',subcategory:'베트남',address,...position,initialRating:5,tags:['강추업소'],memberBenefit:true}],reviews:[{id:'r',placeId:'local',rating:4,text:'후기 보존'}]};
 const before=JSON.stringify(data),raw=(id,name,extra={})=>({id,displayName:name,types:['restaurant'],formattedAddress:address,location:position,rating:4.5,userRatingCount:20,businessStatus:'OPERATIONAL',...extra});
 const records=[raw('g-local','회원 등록 식당',{priceLevel:'EXPENSIVE'}),raw('cheap','저렴한 Google 식당',{priceLevel:'INEXPENSIVE'}),raw('unknown','가격 미확인 식당',{rating:5}),raw('mood','분위기 식당',{editorialSummary:'Great atmosphere and lovely interior.',priceLevel:'MODERATE'})];
 let request;w.google={maps:{places:{Place:class{static async searchByText(r){request=r;return {places:records};}constructor({id}){this.id=id;}async fetchFields(){Object.assign(this,records.find(r=>r.id===this.id));}}}}};
 const rows=await w.AIGoogleSearch.search(cheap,{places:data.places});assert(request.fields.includes('priceRange'));assert.equal(rows[0].placeId,'cheap');assert.equal(rows.at(-1).placeId,'unknown');assert(rows.memberUpdates.has('local'),'deduped Google place enriches member price');
 assert.match(w.AIGoogleSearch.queryFor(banh),/banh mi/);assert.equal(w.AIGoogleSearch.includedType(bakery),'bakery');assert.match(w.AIGoogleSearch.queryFor(rental),/motorbike rental/);assert.match(w.AIGoogleSearch.queryFor(hotel),/4 star hotel/);
 const wrongHotel=raw('hotel','3 star Hotel',{types:['hotel','lodging'],editorialSummary:'3-star hotel'});assert.equal(w.AIGoogleSearch.rowsFrom([wrongHotel],hotel).length,0);
 const uncertainHotel=raw('hotel','Hotel',{types:['hotel','lodging'],rating:4});assert.equal(w.AIGoogleSearch.rowsFrom([uncertainHotel],hotel)[0].insights.hotelClass.kind,'unknown');
 const boss={id:'boss',name:'BOSS Restaurant & KTV',address:'27-29-31 Đ. số 9A, Hồ Chí Minh',...position};
 const bossGoogle=raw('boss-google',boss.name,{formattedAddress:boss.address});
 assert.equal(w.AIGoogleSearch.rowsFrom([bossGoogle],cheap,{places:[boss]}).length,0,'same name, numbered street and nearby pin deduplicates');
 assert.equal(w.AIGoogleSearch.rowsFrom([bossGoogle],cheap,{places:[{...boss,address:'29 Đ. số 9A, Hồ Chí Minh'}]}).length,1,'different street number keeps separate branches');
 w.data=data;run('db=()=>data;state.sharedDbLoading=false;state.city="hcmc";');let current=cheap;w.fetch=async()=>({ok:true,json:async()=>({intent:current})});
 const input=w.document.getElementById('aiMapQuestion'),form=w.document.getElementById('aiMapForm'),list=w.document.getElementById('aiMapResults');
 const submit=async text=>{input.value=text;input.dispatchEvent(new w.Event('input'));form.dispatchEvent(new w.Event('submit',{cancelable:true}));await new Promise(r=>setTimeout(r,25));};
 await submit('가격 저렴한 식당');assert.equal(w.document.querySelector('.aiResult').dataset.googlePlaceId,'cheap','explicit price order overrides member-first grouping');assert.match(w.document.querySelector('[data-place-id="local"] .aiPrice').textContent,/높은 가격대/);assert.equal(w.document.querySelectorAll('.aiResult').length,4);assert(!list.classList.contains('aiRankingPending'));
 input.focus();await new Promise(r=>setTimeout(r,5));assert.equal(w.document.querySelector('.aiResult').dataset.googlePlaceId,'cheap','focus preserves prices and sorting');assert.match(w.document.querySelector('[data-place-id="local"] .aiPrice').textContent,/높은 가격대/);
 current=atmosphere;await submit('분위기 좋은 식당');assert.equal(w.document.querySelector('.aiResult').dataset.googlePlaceId,'mood');assert.match(list.textContent,/Great atmosphere/);
 current=ferry;await submit('호치민에서 푸꿕 배편');assert.equal(w.document.querySelectorAll('.aiTravelAnswer a').length,2);assert.match(list.textContent,/하띠엔/);assert(!list.textContent.includes('찾고 싶은 업소'));
 current=budget;records.splice(0,records.length,raw('karaoke','Karaoke Test',{types:['karaoke']}));await submit('로컬 가라오케 500만동');assert.equal(w.document.querySelectorAll('.aiResult').length,1);assert.match(w.document.getElementById('aiMapNote').textContent,/총액/);assert.match(list.textContent,/가격 정보 미확인/);assert.match(list.textContent,/로컬 운영 여부 미확인/);assert(!list.textContent.includes('Google 업종 확인 · 로컬 KTV'));
 w.data={places:[{...data.places[0],category:'stay',subcategory:'호텔'}],reviews:[]};current=hotel;records.splice(0,records.length,raw('g-local','회원 등록 식당',{types:['hotel'],editorialSummary:'3-star hotel'}),uncertainHotel);await submit('1군 4성급 호텔');assert.equal(w.document.querySelectorAll('.aiMemberResult').length,0,'incompatible star class discovered during enrichment removes candidate');assert.match(w.document.getElementById('aiMapTitle').textContent,/4성급 안내 0곳 · 성급 문의 1곳/);input.focus();assert.equal(w.document.querySelectorAll('.aiMemberResult').length,0,'refocus cannot restore incompatible candidate');w.data=data;
 let finish;w.AIGoogleSearch.search=()=>new Promise(r=>{finish=r});current=cheap;await submit('저렴한 식당 찾기');input.value='다른 질문';input.dispatchEvent(new w.Event('input'));finish(rows);await new Promise(r=>setTimeout(r,10));assert.equal(w.document.querySelectorAll('.aiResult').length,0,'late ranking response cannot replace edited query');
 assert.equal(JSON.stringify(data),before);dom.window.close();
 console.log('PASS six screenshot intents, price ranges and unknowns, hotel stars separate from ratings, budget inquiry, global intent ranking, repeat focus, stale cancellation and preserved reviews');
})().catch(e=>{console.error(e);process.exitCode=1});
