const fs=require('fs'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const pause=()=>new Promise(r=>setTimeout(r,0));
async function check(mobile){
 const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{url:'https://example.test',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window,d=w.document;
 w.matchMedia=q=>({matches:q.includes('min-width:901')?!mobile:q.includes('max-width:900')?mobile:false});let inserts,subscribe,fetches=[],fail=false,bindings=[];
 class Client{channel(){return{on(_,__,fn){inserts=fn;return this},subscribe(fn){subscribe=fn;queueMicrotask(()=>fn('SUBSCRIBED'));return this}}}removeAllChannels(){return Promise.resolve()}disconnect(){return Promise.resolve()}}
 w.ViettripRealtime={RealtimeClient:Client};w.eval(fs.readFileSync('assets/js/body-sheet-drag.js','utf8'));const originalBind=w.BodySheetDrag.bind;w.BodySheetDrag.bind=(p,o)=>{bindings.push([p,o]);originalBind(p,o)};d.querySelector('#chatDock').getBoundingClientRect=()=>({height:parseFloat(d.querySelector('#chatDock').style.getPropertyValue('--chat-height'))||62,right:900});w.ListLayout={setCollapsed(){}};w.MapMembership={memberId:'me',refresh:async()=>true};w.rememberedMemberNickname=()=>'회원';w.getDeviceId=()=> '123e4567-e89b-42d3-a456-426614174000';
 w.SUPABASE_URL='https://example.test';w.SUPABASE_HEADERS={};
 w.fetch=async(url,opt={})=>{fetches.push({url,opt});if(url.includes('map_chat_grades'))return{ok:true,json:async()=>JSON.parse(opt.body).p_message_ids.map(id=>({id,level:3}))};if(opt.method==='POST'){if(fail)throw Error('offline test');const data=JSON.parse(opt.body);return{ok:true,json:async()=>({id:data.p_request_id,nickname:data.p_nickname,body:data.p_body,created_at:new Date().toISOString()})}}return{ok:true,json:async()=>[]}};
 w.eval(fs.readFileSync('assets/js/chat-dock.js','utf8'));assert.equal(d.querySelector('.top .aiMapSearch'),null);assert.equal(d.querySelector('#detail').parentElement.id,'businessSide');assert.equal(d.querySelector('#areaLegend').parentElement.id,'businessSide');assert.equal(d.querySelector('.mapwrap #areaLegend'),null);assert.equal(d.querySelector('#adminBtn').closest('#businessSide'),null);
 assert.equal(d.querySelector('#chatForm .chatNickname'),null);assert.equal(d.querySelector('#chatForm input[autocomplete=nickname]'),null);d.querySelector('#chatToggle').click();await pause();await pause();assert.match(d.querySelector('#chatStatus').textContent,/실시간/);assert.equal(d.querySelector('#chatContent').hidden,false);if(mobile)assert.equal(Number(d.querySelector('#chatGrip').getAttribute('aria-valuenow')),Number(d.querySelector('#chatGrip').getAttribute('aria-valuemax')),'mobile opens at the full usable height');
 assert.equal(d.querySelector('#chatRetry').hidden,true,'no retry control when subscribed');
 w.ChatDock.close();
 inserts({new:{id:'unread',sender_id:'other',nickname:'회원',body:'새 대화',created_at:new Date(Date.now()+100).toISOString()}});
 assert.equal(d.querySelector('#chatLauncher .chatUnreadBadge').textContent,'1');assert.equal(d.querySelector('#chatLauncher .chatUnreadBadge').hidden,false);
 assert(!d.querySelector('.chatMessage').classList.contains('chatMessageMine'),'matching nickname must not imply ownership');
 inserts({new:{id:'unread',sender_id:'other',nickname:'회원',body:'새 대화',created_at:new Date(Date.now()+100).toISOString()}});
 assert.equal(d.querySelector('#chatLauncher .chatUnreadBadge').textContent,'1','duplicate events do not increment unread');
 inserts({new:{id:'mine-history',sender_id:'me',nickname:'옛 닉네임',body:'내 대화',created_at:new Date().toISOString()}});
 assert.equal(d.querySelectorAll('.chatMessageMine').length,1,'member identity aligns old messages');
 w.ChatDock.open();assert.equal(d.querySelector('#chatLauncher .chatUnreadBadge').hidden,true,'opening latest messages clears unread');
 inserts({new:{id:'x',nickname:'<img onerror=evil()>',body:'<script>evil()</script>',created_at:new Date().toISOString()}});assert.equal(d.querySelectorAll('#chatMessages script,#chatMessages img').length,0);assert.match(d.querySelector('#chatMessages').textContent,/<script>/);await pause();assert.equal(d.querySelector('.chatRank').getAttribute('aria-label'),'상병');assert.equal(d.querySelector('.chatRank').textContent,'');assert.equal(d.querySelector('.chatRank .rankBars').children.length,3);assert.equal(d.querySelector('.chatMessage header').firstElementChild.classList.contains('chatRank'),true);
 d.querySelector('#chatNickname').value='회원';d.querySelector('#chatMessage').value='안녕하세요';fail=true;d.querySelector('#chatForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await pause();assert.equal(d.querySelector('#chatMessage').value,'안녕하세요');const first=JSON.parse(fetches.filter(x=>x.url.includes('send_map_chat')).at(-1).opt.body).p_request_id;
 fail=false;d.querySelector('#chatForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await pause();assert.equal(JSON.parse(fetches.filter(x=>x.url.includes('send_map_chat')).at(-1).opt.body).p_request_id,first);assert.equal(d.querySelector('#chatMessage').value,'');assert(d.querySelector('.chatMessageMine'),'successful send appears on right');
 const count=fetches.length;d.querySelector('#aiTab').click();await pause();assert.equal(d.querySelector('#peopleChat').hidden,true);assert.equal(d.querySelector('#aiChat').hidden,false);assert.equal(fetches.length,count,'AI tab must not send a public message');
 d.querySelector('#detail').classList.add('show');await pause();assert.equal(d.querySelector('#businessSide').dataset.detail,'true');assert.equal(d.querySelector('#chatContent').hidden,mobile,'desktop details and chat can stay open together');
 d.querySelector('#chatGrip').dispatchEvent(new w.KeyboardEvent('keydown',{key:'End'}));assert.equal(d.querySelector('#chatContent').hidden,false);d.querySelector('#chatFold').click();assert.equal(d.querySelector('#chatContent').hidden,true);
 assert(bindings[0][1].anywhere);const pointer=(target,type,y)=>{const e=new w.Event(type,{bubbles:true,cancelable:true});Object.assign(e,{pointerId:1,pointerType:'mouse',isPrimary:true,button:0,clientX:100,clientY:y});target.dispatchEvent(e)};pointer(d.querySelector('#chatGrip'),'pointerdown',700);pointer(w,'pointermove',400);pointer(w,'pointerup',400);assert.equal(d.querySelector('#chatContent').hidden,!mobile,'only mobile keeps vertical sheet dragging');if(!mobile){d.querySelector('#chatLauncher').click();assert.equal(d.querySelector('#chatContent').hidden,false);assert.equal(d.querySelector('#chatDock').inert,false);w.ChatDock.close();assert.equal(d.querySelector('#chatDock').inert,true);}d.querySelector('#chatQuickAi').click();assert.equal(d.querySelector('#aiTab').getAttribute('aria-selected'),'true');assert.equal(d.querySelector('#chatContent').hidden,false);d.querySelector('#chatQuickPeople').click();assert.equal(d.querySelector('#peopleTab').getAttribute('aria-selected'),'true');await pause();await pause();
 w.rememberedMemberNickname=()=>'';let remembered='';w.rememberMemberNickname=name=>{remembered=name};
 const dialog=d.querySelector('#chatNameDialog');dialog.showModal=()=>{dialog.open=true};dialog.close=()=>{dialog.open=false};
 d.querySelector('#chatMessage').value='첫 메시지';const sentBefore=fetches.filter(x=>x.url.includes('send_map_chat')).length;
 d.querySelector('#chatForm').dispatchEvent(new w.Event('submit',{cancelable:true}));assert.equal(dialog.open,true);d.querySelector('#chatNameCancel').click();assert.equal(d.querySelector('#chatMessage').value,'첫 메시지');assert.equal(fetches.filter(x=>x.url.includes('send_map_chat')).length,sentBefore);
 d.querySelector('#chatForm').dispatchEvent(new w.Event('submit',{cancelable:true}));d.querySelector('#chatNickname').value='새회원';d.querySelector('#chatNameForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await pause();await pause();assert.equal(remembered,'새회원');assert.equal(fetches.filter(x=>x.url.includes('send_map_chat')).length,sentBefore+1);assert.equal(dialog.open,false);w.ChatDock.close();dom.window.close();
}
(async()=>{await check(false);await check(true);console.log('PASS chat desktop/mobile DOM: modes, history, safe rendering, retry idempotency, retained draft, docked detail, keyboard resizing')})().catch(e=>{console.error(e);process.exitCode=1});
