const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
async function main(){
 const events={},notices=[],badges=[],opened=[],posted=[];
 const self={addEventListener:(name,fn)=>events[name]=fn,location:{origin:'https://example.test'},registration:{showNotification:async(...args)=>notices.push(args)},navigator:{setAppBadge:async n=>badges.push(n)},clients:{claim:async()=>{},matchAll:async()=>[],openWindow:async url=>opened.push(url)}};
 vm.runInNewContext(fs.readFileSync('sw.js','utf8'),{self,URL,Response,fetch});let work;
 events.push({data:{json:()=>({messageId:'11111111-1111-4111-8111-111111111111',body:'답장이 왔습니다',count:3,url:'https://evil.test/'})},waitUntil:p=>work=p});await work;assert.equal(notices.length,1);assert.equal(badges[0],3);assert.equal(notices[0][1].data.url,'/?chat_reply=11111111-1111-4111-8111-111111111111');
 events.notificationclick({notification:{data:notices[0][1].data,close(){}},waitUntil:p=>work=p});await work;assert.equal(opened[0],'https://example.test/?chat_reply=11111111-1111-4111-8111-111111111111');
 self.clients.matchAll=async()=>[{url:'https://example.test/',focus:async()=>{},postMessage:d=>posted.push(d)}];events.notificationclick({notification:{data:notices[0][1].data,close(){}},waitUntil:p=>work=p});await work;assert.equal(posted[0].type,'chat-push-open');assert.equal(opened.length,1);
 const dom=new JSDOM('<button id="chatBadgePermission"></button>',{url:'https://example.test',runScripts:'outside-only'}),w=dom.window;let prompts=0,subscribes=0,unsubscribes=0;const calls=[];
 w.PushManager=function(){};w.Notification={permission:'default',requestPermission:async()=>{prompts++;return 'granted'}};const sub={endpoint:'https://fcm.googleapis.com/test',toJSON:()=>({endpoint:'https://fcm.googleapis.com/test'}),unsubscribe:async()=>{unsubscribes++}};const reg={pushManager:{getSubscription:async()=>null,subscribe:async()=>{subscribes++;return sub}}};Object.defineProperty(w.navigator,'serviceWorker',{value:{getRegistration:async()=>undefined,register:async()=>reg,ready:Promise.resolve(reg),addEventListener(){}}});w.SUPABASE_URL='https://api.test';w.SUPABASE_HEADERS={apikey:'public'};w.getDeviceId=()=> 'private-device';w.MapMembership={refresh:async()=>true};w.ChatDock={syncPush(){}};w.ChatComfort={feedback:message=>{throw Error(message)}};
 w.fetch=async(url,options)=>{calls.push(url);return{ok:true,json:async()=>url.endsWith('/config')?{publicKey:'BA'}:{ids:[],count:0,ok:true}}};w.eval(fs.readFileSync('assets/js/chat-push.js','utf8'));await new Promise(r=>setTimeout(r,0));assert.equal(prompts,0,'no unsolicited permission prompt');await w.document.querySelector('button').onclick();assert.equal(prompts,1);assert.equal(subscribes,1);assert(calls.some(x=>x.endsWith('/subscribe')));assert.match(w.document.querySelector('button').textContent,/켜짐/);await w.document.querySelector('button').onclick();assert.equal(unsubscribes,1);assert(calls.some(x=>x.endsWith('/unsubscribe')));dom.window.close();console.log('PASS push: opt-in only, subscribe/unsubscribe, push-event display, badge, safe notification navigation');
}
main().catch(e=>{console.error(e);process.exitCode=1});
