// Entirely local fixtures: no production reads/writes or made-up published alerts.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom'),D=require('../assets/js/road-condition-data.js');
(async()=>{
 let now=Date.parse('2026-10-02T07:00:00Z');
 const stamp=offset=>new Date(now+offset).toISOString();
 const record={id:'test-flood',kind:'flood',city:'hcmc',title:'<img src=x onerror=alert(1)>',description:'Local-only road fixture; no real incident.',geometry:{type:'Point',coordinates:[106.7,10.77]},observedAt:stamp(-3600000),verifiedAt:stamp(-1800000),expiresAt:stamp(3600000),source:{type:'community',name:'local test',url:'https://fixture.invalid/1'},reviewedBy:'test'};
 const flood=()=>({...record,geometry:{...record.geometry},source:{...record.source}});
 assert(D.valid(record));
 for(const patch of [{id:undefined},{source:{...record.source,url:'javascript:alert(1)'}},{source:{...record.source,url:'https://a:b@example.com'}},{reviewedBy:''},{expiresAt:stamp(7*3600000)},{geometry:{type:'Point',coordinates:[10.77,106.7]}},{geometry:{type:'Polygon',coordinates:[[[106.7,10.77],[106.8,10.77],[106.8,10.78],[106.7,10.79]]]}}])assert(!D.valid({...flood(),...patch}));
 assert.equal(D.active({incidents:[{...flood(),verifiedAt:stamp(1000)}]},now).length,0);
 assert.equal(D.active({incidents:[record]},now,'hanoi').length,0);
 assert.throws(()=>D.parse({version:1,updatedAt:stamp(0),incidents:[record,record]}));
 const construction={...flood(),id:'test-work',kind:'construction',title:'Road work fixture',geometry:{type:'LineString',coordinates:[[106.7,10.77],[106.71,10.78]]},expiresAt:stamp(2*86400000)};
 const polygon={...flood(),id:'test-area',geometry:{type:'Polygon',coordinates:[[[106.7,10.77],[106.71,10.77],[106.71,10.78],[106.7,10.77]]]}};
 let payload={version:1,updatedAt:stamp(0),incidents:[record,construction,polygon]},offline=false,calls=0,clipboard='';
 const dom=new JSDOM('<div class="mapwrap"><div class="browseResultBar"></div></div>',{url:'https://example.test',runScripts:'outside-only'}),w=dom.window;
 w.Date.now=()=>now;w.setInterval=()=>1;w.clearInterval=()=>{};
 w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')};
 w.HTMLElement.prototype.scrollIntoView=function(){};
 w.safeStorageGet=k=>w.localStorage.getItem(k);w.safeStorageSet=(k,v)=>w.localStorage.setItem(k,v);
 w.CITY_DATA={hcmc:{label:'호치민'},hanoi:{label:'하노이'}};
 const traffic=[],markers=[],lines=[],polygons=[];
 class Overlay{constructor(o){Object.assign(this,o)}setMap(m){this.map=m}getMap(){return this.map}addListener(k,f){this[k]=f}}
 w.google={maps:{TrafficLayer:class extends Overlay{constructor(o){super(o);traffic.push(this)}},Marker:class extends Overlay{constructor(o){super(o);markers.push(this)}},Polyline:class extends Overlay{constructor(o){super(o);lines.push(this)}},Polygon:class extends Overlay{constructor(o){super(o);polygons.push(this)}},Size:class{},Point:class{}}};
 const map={setOptions(o){this.cursor=o.draggableCursor},get(){return 'grab'},panTo(p){this.center=p},setZoom(z){this.zoom=z}};w.state={map,city:'hcmc'};
 for(const k of ['cancelPendingMapWork','closeSystemInfo','closeDetailPanel','closeAreaPanel','closeMobileBusinessList','setMobileLegendExpanded','cancelRegisterMode'])w[k]=()=>{};
 w.fetch=async(url,opts)=>{assert.equal(url,'./assets/data/road-conditions.json');assert(!opts.method,'reporting never sends a POST or edits production data');calls++;if(offline)throw Error('offline');return {ok:true,text:async()=>JSON.stringify(payload)}};
 Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async text=>{clipboard=text}}});
 const flush=()=>new Promise(r=>setImmediate(r)),el=id=>w.document.getElementById(id);
 for(const file of ['road-condition-data','road-conditions'])vm.runInContext(fs.readFileSync('assets/js/'+file+'.js','utf8'),dom.getInternalVMContext());
 await flush();assert.equal(markers.filter(m=>m.map).length,3);assert.equal(lines.length,1);assert.equal(polygons.length,1);assert.equal(traffic.length,0,'traffic is opt in');
 el('roadConditionsOpen').click();assert(el('roadConditionsDialog').open);assert.equal(el('roadIncidentList').querySelectorAll('img').length,0,'source strings cannot create markup');assert.equal(calls,1,'map renders and dialog opens coalesce feed reads');
 el('roadTraffic').click();assert.equal(traffic.length,1);assert.equal(traffic[0].getMap(),map);w.RoadConditions.sync();assert.equal(traffic.length,1);el('roadTraffic').click();assert.equal(traffic[0].getMap(),null);
 el('roadFlood').click();assert.equal(markers.filter(m=>m.map).length,1,'flood toggle removes markers and polygons only');assert.equal(polygons[0].map,null);el('roadFlood').click();
 w.state.city='hanoi';w.RoadConditions.sync();assert.equal(markers.filter(m=>m.map).length,0);assert.match(el('roadIncidentList').textContent,/하노이/);w.state.city='hcmc';w.RoadConditions.sync();
 offline=true;await w.RoadConditions.refresh(true);assert.match(el('roadFeedStatus').textContent,/이전에 받은/);assert.equal(markers.filter(m=>m.map).length,3,'failed fetch retains unexpired verified data');
 now+=2*3600000;w.RoadConditions.sync();assert.equal(markers.filter(m=>m.map).length,1,'expired flood cannot survive an outage');
 offline=false;payload={bad:'schema'};await w.RoadConditions.refresh(true);assert.equal(markers.filter(m=>m.map).length,1,'invalid response cannot erase good data');
 payload={version:1,updatedAt:stamp(0),incidents:[]};await w.RoadConditions.refresh(true);assert.equal(markers.filter(m=>m.map).length,0,'authoritative empty feed retracts old records');
 el('roadReportOpen').click();assert(el('roadReportDialog').open);assert(!el('roadConditionsDialog').open);
 el('roadReportPick').click();assert(w.RoadConditions.isPicking());assert.equal(map.cursor,'crosshair');
 assert(w.RoadConditions.handleMapClick({latLng:{lat:()=>10.78,lng:()=>106.71},stop(){}}));el('roadPickConfirm').click();assert(!w.RoadConditions.isPicking());assert(el('roadReportDialog').open);assert.equal(map.cursor,'grab');
 el('roadReportName').value='테스트 교차로';el('roadReportBody').value='현장 사진과 통행 상태를 확인하는 테스트';
 el('roadReportForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await flush();assert.match(clipboard,/106.710000/);assert.match(el('roadDraftStatus').textContent,/아직 전송되지/);assert.equal(w.localStorage.length,1,'only layer preferences persist; no report coordinates or text');
 el('roadReportTime').value='2026-10-03T09:00';el('roadReportForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await flush();assert(el('roadDraftResult').hidden,'invalid edited report cannot retain a stale copy');
 el('roadReportPick').click();el('roadPickCancel').click();assert(!w.RoadConditions.isPicking());assert(el('roadReportDialog').open);
 w.dispatchEvent(new w.Event('pagehide'));dom.window.close();
 console.log('PASS road overlays: source validation, expiry, city/toggle filtering, outages, traffic opt-in, XSS safety, map picking and explicit cafe handoff; no production writes');
})().catch(e=>{console.error(e);process.exitCode=1});
